# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name=b'\xe7\xab\xa0\xe8\x8a\x82')),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'verbose_name_plural': 'dictionaries',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kana', models.CharField(max_length=30, verbose_name=b'\xe5\x81\x87\xe5\x90\x8d')),
                ('kanji', models.CharField(max_length=30, verbose_name=b'\xe6\xb1\x89\xe5\xad\x97')),
                ('meaning', models.CharField(max_length=100, verbose_name=b'\xe6\x84\x8f\xe6\x80\x9d')),
                ('reading', models.CharField(max_length=100, verbose_name=b'\xe8\xaf\xbb\xe6\xb3\x95')),
            ],
        ),
    ]
