# Generated by Django 2.0 on 2017-12-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_selectedword_last_review_times_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedword',
            name='ignored',
            field=models.BooleanField(default=False, verbose_name='无视'),
        ),
    ]
