# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20171201_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='dictionary',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Dictionary'),
            preserve_default=False,
        ),
    ]
