# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_chapter_dictionary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='reading',
        ),
        migrations.AddField(
            model_name='word',
            name='marking',
            field=models.CharField(default='', max_length=100, verbose_name=b'\xe6\xa0\x87\xe6\xb3\xa8'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Dictionary', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe5\xad\x97\xe5\x85\xb8'),
        ),
    ]
