# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_auto_20171201_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='chapter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Chapter', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe7\xab\xa0\xe8\x8a\x82'),
            preserve_default=False,
        ),
    ]
