# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0005_word_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='marking',
            field=models.CharField(max_length=100, verbose_name=b'\xe5\x81\x87\xe5\x90\x8d\xe6\xa0\x87\xe6\xb3\xa8'),
        ),
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.TextField(verbose_name=b'\xe6\x84\x8f\xe6\x80\x9d'),
        ),
    ]
