# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0009_auto_20171204_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedword',
            name='origin',
        ),
        migrations.AlterField(
            model_name='selectedword',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='selected_words', serialize=False, to='dictionaries.Word', verbose_name='原词'),
        ),
        migrations.AlterField(
            model_name='word',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='dictionaries.Chapter', verbose_name='所属章节'),
        ),
        migrations.AlterField(
            model_name='word',
            name='characteristic',
            field=models.CharField(choices=[('0', '名词'), ('1', '代词'), ('2', '副词'), ('3', '专'), ('4', '叹'), ('5', '短语')], max_length=1, verbose_name='词性'),
        ),
    ]
