# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0010_auto_20171205_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedword',
            old_name='id',
            new_name='origin',
        ),
    ]
