# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0011_auto_20171205_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedword',
            name='correct_rate',
            field=models.IntegerField(blank=True, verbose_name='正确率'),
        ),
        migrations.AlterField(
            model_name='selectedword',
            name='origin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dictionaries.Word', verbose_name='原词'),
        ),
        migrations.AlterField(
            model_name='selectedword',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_words', to='dictionaries.Profile', verbose_name='所属'),
        ),
    ]
