# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0012_auto_20171205_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedword',
            name='correct_rate',
            field=models.IntegerField(null=True, verbose_name='正确率'),
        ),
    ]
