# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0013_auto_20171205_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedword',
            name='last_checked_at',
            field=models.DateTimeField(null=True, verbose_name='最后记忆时间'),
        ),
        migrations.AlterField(
            model_name='selectedword',
            name='last_wrong_at',
            field=models.DateTimeField(null=True, verbose_name='最后错误时间'),
        ),
    ]
