# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0014_auto_20171205_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedword',
            name='next_check_point',
            field=models.DateTimeField(null=True, verbose_name='下次检查点'),
        ),
        migrations.AlterField(
            model_name='word',
            name='characteristic',
            field=models.CharField(choices=[('0', '名'), ('1', '代'), ('2', '副'), ('3', '专'), ('4', '叹'), ('5', '短语')], max_length=1, verbose_name='词性'),
        ),
    ]
