# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0016_auto_20171209_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='characteristic',
            field=models.CharField(choices=[('0', '名'), ('1', '代'), ('2', '副'), ('3', '形1'), ('4', '形2'), ('5', '动1'), ('6', '动2'), ('7', '动3'), ('8', '专'), ('9', '叹'), ('10', '连'), ('11', '连体'), ('12', '疑'), ('99', 'phrase')], max_length=2, verbose_name='词性'),
        ),
    ]
